blank_issues_enabled: false
contact_links:
  - name: 💬 Grupo da Comunidade (WhatsApp)
    url: https://chat.whatsapp.com/4y7xoORc5NWHxGc3082SBB
    about: Entre no nosso grupo para bater papo em tempo real e tirar dúvidas rápidas.
  - name: 🌐 Site Oficial do Madeira Hacker Club
    url: https://madeirahacker.club
    about: Conheça nosso espaço, projetos e formas de apoio.
